model: "tic_promptmodel"
dataset: "coco"
dataset_path: '/path/to/COCO/dataset'
kodak_path: 'raw_images'
input_resolution: 256
epochs: 100
steps: 1200
learning_rate: 5.e-5
num_workers: 4
quality_level: 8
batch_size: 16
test_batch_size: 16
aux_learning_rate: 1.e-3
patch_size: 256
cuda: True
gpu_id: 0
save: True
clip_max_norm: 1.0
name: "NAME"
exp_name: "NAME"
seed: 42
root: "/kaggle/working/Transformer_VariableROI"
checkpoint: "/kaggle/input/transformervariableroi/pytorch/default/1/transformer_variablerate_roi.pth.tar"
LOCATION: 'prepend'
DEEP: True
NUM_TOKENS: 16
INITIATION: 'random'
PROJECT: -1
DROPOUT: 0.
TRANSFER_TYPE: 'prompt'
ARCHITECT: 'both'
WINDOW: 'same' 
RETURN_ATTENTION: False
MASK_DOWNSAMPLE: 2